### ISSUE TITLE
気になったところ

### ISSUE THREAD

**Issue by 1plus4** [Fuku-san/PrivacyPolicy#2]
- メールアドレスは取ってない、取りたい？
- 41行目 クッキーだけじゃなくWeb Storageも利用している。認証のセッション管理には後者を使っている。
- 67行目 漠然とした言い回しで怪しい。
- 68行目 怪しい。クッキーやWeb Storageはクライアント端末に認証情報を置いている。

**Comment by shoe116** [comment]
メアド、今んとこ使わないよね。
必要になるとすれば、予約フォーム作ってメールするところくらいか

**Comment by shoe116** [comment]
必須にすると、アイドルの子が使いにくくなっちゃう気がする。
